name: Linux CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  check-format:
    strategy:
      fail-fast: false
      matrix:
        crystal_version:
          - 1.2.2
          - 1.3.2
          - 1.4.1
          - latest
          - nightly
        experimental:
          - false
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Format
        run: crystal tool format --check
